### ISSUE TITLE
Difficulty with acceptance tests

### ISSUE THREAD

**Issue by HeroicEric** [poteto/ember-cli-flash#112]
Surely I'm doing something wrong here but I cannot figure out what it is :smile: 

I've got a button that triggers an action to do something asynchronous, like save a model. When the promise resolves, I'd like to create a flash message to either let the user know that what they did succeeded or that it failed.

When I'm trying to write an acceptance test to cover this behavior, I'm running into some issues.

We're using Mocha in this project so I created an example app that demonstrates the behavior I'm experiencing with mocha https://github.com/HeroicEric/ember-cli-flash-and-mocha/pull/1 Basically, whenever the action is triggered, I'm getting `Error: timeout of 2000ms exceeded.`

I also tried to see if it was just an issue with Mocha by recreating the same situation with Qunit , which can be found at https://github.com/HeroicEric/ember-cli-flash-and-mocha/pull/2. Qunit seems to avoid the timeout issue but doesn't move to the `andThen` until the flash message has disappeared.

I will update the README if somebody can help me clear this up :smiley_cat:

**Comment by xtian** [comment]
I'm also having this issue.

**Comment by poteto** [comment]
Heya, apologies for the delay. This should be fixed with `1.3.8`

**Comment by HeroicEric** [comment]
@poteto confirm

**Comment by JakeDluhy** [comment]
I'm seeing this again `ember-cli 2.6.1`, `ember-mocha 0.10.2`, `ember-cli-flash 1.3.15` . andThen in acceptance tests are waiting for the flash to resolve. I'm trying to test that the flash shows up through jquery selector.

I created a basic demo app to show this. https://github.com/JakeDluhy/flash-demo
Just check it out and run the tests.

Thanks!

**Comment by Rsullivan00** [comment]
The waiting for flash messages to dismiss themselves in acceptance tests issue was happening for me on `ember-cli 2.9.1` and `ember-cli-flash 1.4.2`. Downgrading to `1.3.15` solved the issue.

**Comment by sbatson5** [comment]
@Rsullivan00 Do you have an example of it failing?

**Comment by Rsullivan00** [comment]
I don't have a dummy app that shows the behavior. If I get a chance, I might try to reproduce on an empty app.

**Comment by Rsullivan00** [comment]
I've been unable to reproduce my issue on a new app on both the latest versions of packages, and the exact versions of my app (`ember-cli@2.12.1`/`ember-cli-flash@1.4.2` and `ember-cli@2.9.1` and `ember-cli-flash@1.3.17`).
