### ISSUE TITLE
Message doesn't disapear on IE9+

### ISSUE THREAD

**Issue by bcecchinato** [poteto/ember-cli-flash#114]
Hi there !

I'm having an issue with IE9+ that makes the message not auto-closing after a given timeout.
We've set the timeout to 10000ms, but it seems that when there is no `run.later` call, then the message is displayed way more longer.

I've found a solution using `setTimeout` instead of `run.later` that is working (see https://github.com/bcecchinato/ember-cli-flash/commit/fc335999617e0ea296be3574bd09712fae9fe223).

But I don't really like my fix. Have you already seen something identical ?

Regards,

**Comment by bcecchinato** [comment]
It seems that there is a side effect on tests as it is not encapsulated in a run-loop (occurs when auto-runloop is disable).

**Comment by sbatson5** [comment]
@bcecchinato were you ever able to resolve this issue? Are we good to close this?

**Comment by bcecchinato** [comment]
@sbatson5 We ended up keeping `setTimeout` instead of `Ember.run.later` for the trigger. So yes you can close this issue.
