### ISSUE TITLE
Error in acceptance tests when calling for flash

### ISSUE THREAD

**Issue by JakeDluhy** [poteto/ember-cli-flash#124]
I'm working on an application, using ember-cli-flash. It's working well, however while writing acceptance tests I'm running into the error
```
Error: Uncaught Error: Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run (http://localhost:7357/assets/vendor.js:15330)
    at global.onerror (http://localhost:7357/assets/test-support.js:9602:10)
```
at the line that calls the flash.
```
Ember.get(this, 'flashMessages').success(data.meta.success);
```
I tried various things to wrap it in a run loop but it didn't work - notably when I wrapped the line in the run loop, I get an error that the timeout has been exceeded.

Here's a link to the repo: https://github.com/JakeDluhy/ember-boilerplate
and the file: https://github.com/JakeDluhy/ember-boilerplate/blob/master/app/components/user-contact.js

I'd appreciate any insight that you have for me, thanks!

**Comment by poteto** [comment]
Is the test helper installed and present? You should have something like this as your `app/tests/test-helper.js`

```js
import resolver from './helpers/resolver';
import './helpers/flash-message';

import {
  setResolver
} from 'ember-qunit';

setResolver(resolver);
```

**Comment by JakeDluhy** [comment]
I didn't... But I added it so that now my test-helper.js file looks like
```
import resolver from './helpers/resolver';
import './helpers/flash-message';

import { setResolver } from 'ember-mocha';

setResolver(resolver);
```
And it didn't fix it. Is it a problem that I'm using mocha?

**Comment by poteto** [comment]
What version of ember-cli-flash have you installed? You should update to the latest release `1.3.8` if you're not already on it.

**Comment by JakeDluhy** [comment]
I'm on `1.3.8`

**Comment by JakeDluhy** [comment]
Apparently, I was wrapping my entire ajax request in `Ember.run`, when I need to wrap the 'setters' in the promise `.then` (http://stackoverflow.com/questions/31467547/ember-error-while-testing-you-will-need-to-wrap-any-code-with-asynchronous-side).
I was doing
```
Ember.run(function() {
  Ember.$.ajax({
    ...
  })
  .done((data) => {
    flashMessages.success(data.meta.success);
  })
  .fail((xhr) => {
    flashMessages.danger(response.errors.error);
  });
});
```
where I just needed to do
```
Ember.$.ajax({
  ...
})
.done((data) => {
  Ember.run(function() {
    flashMessages.success(data.meta.success);
  });
})
.fail((xhr) => {
  Ember.run(function() {
    flashMessages.danger(response.errors.error);
  });
});
```
Additionally, after I did that I was still having timeout problems, which is related to the duration of the flash. To make my tests run faster, I set the default timeout to a lower number. (I do some extra stuff in the first 500 seconds, hence the 501)
```
if (environment === 'test') {
  ...

  ENV.flashMessageDefaults = {
    timeout: 501
  }
}
```
