### ISSUE TITLE
Allow sticky option to not close on click

### ISSUE THREAD

**Issue by agessner** [poteto/ember-cli-flash#125]
Allow sticky option to not close on any click. Sometimes it has to stay open and close on a button click, for example.
The user needs to be able to copy the message and if it closes on every click that's not possible,

**Comment by blimmer** [comment]
:+1: - I've overridden the default behavior to get this.

**Comment by phammer** [comment]
I fully agree. We did some usability testing, and found that if the text in the message is longer (i.e. especially for error messages and warnings), users tend to move their cursor over the message. Sometimes they just click, sometimes the highlight some text.

**Comment by blimmer** [comment]
Is this implemented now?
