### ISSUE TITLE
flash within an addon

### ISSUE THREAD

**Issue by ksnyde** [poteto/ember-cli-flash#131]
I have an addon -- `ui-bootstrap` -- which consumes ember-cli-flash as a "dependency" with the intent of making flash messages available to its consumers. And while it works fine in the dummy app of the Addon it gives me the following error when I use `ui-bootstrap` in an app:

Cannot read property 'injectionFactories' of undefined. This is in the `flash-messages.js` file:

    var injectionFactories = flashMessageDefaults.injectionFactories;

Even after putting in `flashMessageDefaults` into my `environment.js` I still get this error. How do I fix this without requiring my consumers to have to install **ember-cli-flash** themselves?

**Comment by poteto** [comment]
If it's a dependency it will need to be installed and configured by your addon's consumers.

**Comment by ksnyde** [comment]
I have installed it as a dependency into my addon. Shouldn't that propagate to the consumer of my addon? I have other addons which work this way.

**Comment by ksnyde** [comment]
I thought it was only bower dependencies which would not cascade through addons.

**Comment by ksnyde** [comment]
Ok, I think I've sorted out why it's breaking. The npm dependencies _do_ cascade downward but the way you have setup the default configuration _does not_. I am able to get it to work by just recreating that default configuration but it would be nice if you just included that config as a constant in the `app/initializers/flash-messages.js`

I can send you a PR if that helps.

**Comment by poteto** [comment]
Closed by #134
