### ISSUE TITLE
add base css class to {{flash-message}}

### ISSUE THREAD

**Issue by kellyselden** [poteto/ember-cli-flash#133]
I'm not using bootstrap or foundation. It would be nice to have a more specific way of selecting than: `<div id="ember1749" class="ember-view alert alert-info active">` so it doesn't collide with other potential selectors. I propose "flash-message" so it would be `<div id="ember1749" class="ember-view flash-message alert alert-info active">`. I would be open to doing the PR if it's approved.

**Comment by kellyselden** [comment]
I mean it's not too hard to do `{{flash-message class="flash-message" flash=flash}}`, just curious if you wanted it default.

**Comment by poteto** [comment]
Sure!

**Comment by jfelchner** [comment]
@poteto I ran across this and thought I'd knock this out.  It's a one-liner if you don't care about tests.  Do you want me to specifically test this or no?

**Comment by kellyselden** [comment]
@jfelchner I would test for it, since if it were to be removed accidentally and people started using it, it would be a bug. On the other hand, I am a bit of an extreme tester.

**Comment by wcurtis** [comment]
Great idea - looking forward to this feature
