### ISSUE TITLE
Make injection points configurable

### ISSUE THREAD

**Issue by ssured** [poteto/ember-cli-flash#14]
https://github.com/poteto/ember-cli-flash/blob/40e58c4e99ed12a4b999077d18b01e04bc170929/app/initializers/flash-messages-service.js#L6

The plugin confuses me a little, as it injects everywhere by default, but also offers the plugin as an Ember 1.10 inject.service() property. For me it would be to make the injection points configurable, so I can choose to only inject on routes for instance.

**Comment by poteto** [comment]
Hey, yup that will be addressed in #9

**Comment by poteto** [comment]
Hey @ssured, sorry this took so long! [0.8.3](https://github.com/poteto/ember-cli-flash/releases/tag/0.8.3) now lets you do this.

**Comment by ssured** [comment]
Cool stuff, thanks for your work on this lib!
