### ISSUE TITLE
Depreciation of injectionFactories?

### ISSUE THREAD

**Issue by mattbearman** [poteto/ember-cli-flash#141]
Hi,

Thanks for the awesome plug in!

I've just seen that you've depreciated the auto injection in v1.3.10, does this mean Ember JS will be depreciating this feature in time, or was it just a personal preference? As I can't find anything about it in the Ember blogs.

Thanks,
Matt

**Comment by poteto** [comment]
It is mainly to reduce the amount of "magic" in this addon. It is better to be explicit and to inject the service directly into the things that require it.

**Comment by visoft** [comment]
In Ember 2.3 you get a warning on your deprecation call, "When calling `Ember.deprecate` you must provide `until` in the options"
