### ISSUE TITLE
Overriding defaults in environment.js

### ISSUE THREAD

**Issue by SirZach** [poteto/ember-cli-flash#152]
Hi, I tried overriding defaults in `config/environment.js` with the following:

```javascript
flashMessageDefaults: {
      // flash message defaults
      timeout: 50000,
      extendedTimeout: 0,
      priority: 200,
      sticky: true,
      showProgress: true,

      // service defaults
      type: 'alpaca',
      types: [ 'alpaca', 'notice', 'foobar' ],
      preventDuplicates: false
    }
```

But when I did this, the `.success` method was no longer available on the service.

**Comment by poteto** [comment]
When you add a custom `types` array those will be the only methods available on the service. So `.alpaca` etc

**Comment by SirZach** [comment]
I see. `success` and `error` seem reasonable to always keep around. What about making `types` a concatenated property?

**Comment by poteto** [comment]
The method names are pretty arbitrary, you could easily add `error`, `success` and anything else you wish to it. I think this gives a lot of flexibility, and I would prefer not to concatenate as the whole point of this config option is to let you replace the defaults with new ones.

**Comment by SirZach** [comment]
Right on. Thanks!
