### ISSUE TITLE
Access to flash object on .add() (conflicts with "Fluent API")

### ISSUE THREAD

**Issue by davidgovea** [poteto/ember-cli-flash#154]
First off, thank you for this project - it's been very helpful!

I noticed a change in behavior while upgrading from a far-outdated version:

It looks like the 1.3.7 release ("Fluent API") makes a pattern of returning `this` for chainability.

Previously, `flashMessages.add({ ... })` would return a Flash object. We are defining some dynamic computed properties on this flash object, as well as listening for `didDestroyMessage`.

I submit that obtaining the flash message object is an important feature. Chainability is nice, but I haven't run into pain regarding multiple calls on the service. Maybe what I'm doing is not advisable - just wanted to provide feedback on our use-case. For the time being, I've simply overridden the `add()` method with the old style (returning `this._enqueue(..flashmessage..)`) - addons make it really easy to do so.

Thanks for reading!

**Comment by davidgovea** [comment]
I've been thinking about my approach, and perhaps it's less-than-Embery.
I'm implementing this library into a second project, and I'm going to rely more heavily on components this time (like readme example `{{component flash.componentName}}` rather than dynamically augmenting the flash object)

**Comment by ahx** [comment]
I also have another use-case for accessing the flash object. I am using a custom type, "progress" where I am showing a progress-bar inside the flash message. Currently I am clearing and re-adding the flash-message, but having access to the flash object would be nicer. I am not interested in the chaining aspect.

**Comment by aroberts** [comment]
I also depend on this capability - I need to be able to update the message being displayed. I'll be taking the first approach (overriding `add()` in the service) until flash message object is exposed somewhere via the api.

**Comment by sbatson5** [comment]
@ahx or @aroberts Curious how you would want this used. Would something as simple as an `addAndReturnFlash` method that is not chainable work? I personally haven't had a use-case for accessing the flash object directly

**Comment by ahx** [comment]
@sbatson5 Yes, I think would work for my use-case. Maybe call it `create` instead? Do you know about a use-case for chaining?

**Comment by sbatson5** [comment]
I think `create` is a bit too vague and would easily get used over `add` in instances where people would want to chain. I like being verbose in the case of something like `addAndReturn`. There's probably a better name, but it is escaping me.

**Comment by sbatson5** [comment]
@ahx or @aroberts let me know what you think of: https://github.com/poteto/ember-cli-flash/pull/214

This allows us to keep the chaining but you can still return the flash object:
`const flash = flashMessageService.add({ message: 'foo' }).getFlashObject()`

**Comment by panthony** [comment]
First, thanks for this awesome library.

Like @ahx, I'm trying to use this service to show the user all kind of feedbacks about its actions.

And sometimes it's a progress.

Meaning that this particular message needs to be updated and eventually removed by the application.

So +1 for #214

**Comment by sbatson5** [comment]
Closed by #214
