### ISSUE TITLE
Don't remove flash if mouseover-ed

### ISSUE THREAD

**Issue by poteto** [poteto/ember-cli-flash#18]

**Comment by michalsnik** [comment]
Hi @poteto,
I see that this topic got quiet over a year ago.. Did it stop exactly where you closed #28, or were you doing something about it in a meanwhile?
This sounds like a must have feature to me, it's a bit annoying when it disappears with mouseover. I'm willing to help with this one in a spare time if you'd like.

**Comment by sbatson5** [comment]
@michalsnik Have a PR for this and looking for reviews:
https://github.com/poteto/ember-cli-flash/pull/209

**Comment by sbatson5** [comment]
@michalsnik would you be able to add the last commit directly from #209 to your project and see if it works properly? I've tested it on a few versions of Ember and it seems to work but want to get a practical test in place.

Let me know if you have any questions.

**Comment by sbatson5** [comment]
Closed by #209
