### ISSUE TITLE
Floating messages

### ISSUE THREAD

**Issue by kgish** [poteto/ember-cli-flash#184]
It'd be nice to have an extra option to float the error message instead of positioning in template.

**Comment by jeffrey008** [comment]
What is the difference between floating a message and positioning a message in template?
It would be nice if you can give us some example on "floating a message".

**Comment by kgish** [comment]
Rather than a message embedded on the page (pushes content down and when it disappears all content is pushed up again), a positioned element that can be clicked away.

Does that make more sense?

**Comment by evoactivity** [comment]
That would be down to you @kgish, position fixed and a simple dismiss action.

**Comment by sbatson5** [comment]
@kgish were you able to resolve this issue through styling in your own app?  Have you tried the comment above https://github.com/poteto/ember-cli-flash/issues/184#issuecomment-249151620

**Comment by kgish** [comment]
No, can you please provide some example css that I could borrow?

**Comment by krachtstefan** [comment]
Hi @kgish, I made a small example for you: http://jsbin.com/gibopiqowi/edit?html,css,output
Does this help?

**Comment by kgish** [comment]
Nice example, thanks!
