### ISSUE TITLE
acceptance test that flashMessage is shown

### ISSUE THREAD

**Issue by jelhan** [poteto/ember-cli-flash#202]
I'm not able to write an acceptance test that a flashMessage is shown after an action was triggered. Here is an [Ember Twiddle](https://ember-twiddle.com/11d4be7d8764527b152ea28852f4ef35?numColumns=3&openFiles=templates.application.hbs%2Ccontrollers.application.js%2Ctests.acceptance.my-acceptance-test.js) demonstrating the issue.

A click to button adds a flashMessage. Everything works fine. Just test yourself (scroll down in rendered window). But acceptance test fails. `test/helpers/flash-message.js` is imported in `tests/helpers.js`. I have the same issue locally so it's not related to Ember Twiddle. I just wrote that one to demonstrate easily.

**Comment by sbatson5** [comment]
Hey @jelhan. If you wrap your `click` in another `andThen` it should work for you.

[Here's an example with it rendering and not](https://ember-twiddle.com/373e75d3938964b42334dd7c782a15df?openFiles=tests.acceptance.my-acceptance-test.js%2C)

**Comment by jelhan** [comment]
Ah, yeah of course. Thank's a lot.
