### ISSUE TITLE
Cutting a new release?

### ISSUE THREAD

**Issue by JoshSmith** [poteto/ember-cli-flash#208]
Is it possible to ship a new release that includes fixes from #205?

Thanks @poteto!

**Comment by judngu** [comment]
👍

**Comment by Dhaulagiri** [comment]
@poteto I cut 1.3.17 and published to github if you can publish to NPM

**Comment by poteto** [comment]
Done, thanks! @Dhaulagiri Let me know your npm username and I can add you there as well so you have release rights.

**Comment by JoshSmith** [comment]
Thanks @poteto! 🎉

**Comment by JoshSmith** [comment]
Also thanks @Dhaulagiri 🎈
