### ISSUE TITLE
Releasing 1.4.0

### ISSUE THREAD

**Issue by sbatson5** [poteto/ember-cli-flash#219]
This will include updates found in:

- [x] [Fix Failing Tests]( #218 )
- [x] [Update Acceptance Test Example](https://github.com/poteto/ember-cli-flash/pull/217)
- [x] [Add ability to return flash object](https://github.com/poteto/ember-cli-flash/pull/214)
- [x] [Defer remove on mouse over](https://github.com/poteto/ember-cli-flash/pull/209)
- [x] [Add changelog for release notes](https://github.com/poteto/ember-cli-flash/pull/220)

**Comment by sbatson5** [comment]
@poteto 1.4.0 tag has been pushed, just need to npm publish and we should be good 👍 :shipit:

**Comment by poteto** [comment]
Done, thanks!
