### ISSUE TITLE
Sticky messages not working

### ISSUE THREAD

**Issue by rodrigoboni** [poteto/ember-cli-flash#222]
After showing a message with "sticky" option enabled and hovering it with mouse the message is destroyed.

On debug i find that function leaveMouse (flash-message.js) calls the function resumeTimers on message. Because the timer is negative at this time the message is destroyed...

I need that messages stay visible until user clicks on it.

There is a way to do this ?

(sorry my poor english, i´m studying english yet)

Thanks !

![image](https://cloud.githubusercontent.com/assets/15007343/21436380/564121a4-c865-11e6-8bb4-b78025a75001.png)

**Comment by sbatson5** [comment]
Good catch @rodrigoboni.  Just added a PR to address this!
