### ISSUE TITLE
extendedTimeout doesn't work when sticky equals true

### ISSUE THREAD

**Issue by krachtstefan** [poteto/ember-cli-flash#228]
The `extendedTimeout` option seems not to work when `sticky:true`. Can anyone confirm this?

**Comment by sbatson5** [comment]
@krachtstefan can you clarify? `extendedTimeout` is meant to give an extra padding to the amount of time for the message to disappear and adds the `exiting` class. When `sticky` is `true`, the message won't exit.

Are you looking to have the `extendedTimeout` apply when yo u click the message away?

**Comment by krachtstefan** [comment]
> Are you looking to have the extendedTimeout apply when yo u click the message away?

Yes, my goal is to add animation when someone clicks a message away.

**Comment by wcurtis** [comment]
Just encountered this as well - goal is that messages that are dismissed by tap should have the same exit animation as those that are removed after a timeout.

**Comment by sbatson5** [comment]
@krachtstefan & @wcurtis I had always used the clicking as an immediate dismissal but it shouldn't be too tough to add the same behavior.  PR's are definitely welcome :) but I can try to find some time this weekend

**Comment by wcurtis** [comment]
@sbatson5 🙌

**Comment by zion** [comment]
+1
