### ISSUE TITLE
Repeated mouseEnter and mouseLeave causes flash messages to destroy prematurely

### ISSUE THREAD

**Issue by cmcclure** [poteto/ember-cli-flash#237]
There's an issue in the `deferTimers` method. You subtract the elapsed time from the set `timeout`, but you never reset the `initializedTime`. That means that elapsed time will continue to grow even while the timer is deferred during the hover. Subsequent mouseenters will take larger and larger bites out of the remaining timeout.

https://github.com/poteto/ember-cli-flash/blob/fe56fdad5708737618b627aa4f717390afeb23e9/addon/flash/object.js#L69

Here's a long example...
1. I create a flash message with a 20000ms timeout
  - `initializedTime` is 0 (for the sake of argument)
  - `_getElapsedTime()` is 0
  - `timeout` is 20000
  - `timer` is started
2. After 2000ms, I mouse over it
  - `_getElapsedTime()` is 2000
  - `timeout` is set to 18000
  - `timer` is cancelled
3. After 2000ms, I mouse out
  - `_getElapsedTime()` is 4000
  - `timeout` is 18000
  - `timer` is restarted
4. After 2000ms, I mouse over it
  - `_getElapsedTime()` is 6000
  - `timeout` is set to 12000
  - `timer` is cancelled
5. After 2000ms, I mouse out
  - `_getElapsedTime()` is 8000
  - `timeout` is 12000
  - `timer` is restarted
6. After 2000ms, I mouse over it
  - `_getElapsedTime()` is 10000
  - `timeout` is set to 2000
  - `timer` is cancelled
7. After 2000ms, I mouse out
  - `_getElapsedTime()` is 12000
  - `timeout` is 2000, `timer` is restarted
8. After 2000ms, the flash message will destroy
  - `_getElapsedTime()` is 14000. 6000ms too early

Adding `this._setInitializedTime();` right above line 69 could fix this. Hovering on the flash message would accurately pause the timeout math. However, this means that the progress bar would no longer be accurate. The total time for the flash message would be whatever the timeout was set to plus the amount of time hovered. If this is the intent, then we just need to find a way to address the progress bar animation.

If your intent was to simply not have the message destroy while being hovered, this can be solved in another way entirely. Or possibly, we'd like to have both options with a config variable that determines the behavior. Let me know what the intent was and I'll be happy to patch it.

**Comment by sbatson5** [comment]
Hey @cmcclure, nice catch. Resuming the timer was one of the requirements floated regarding mouseover (https://github.com/poteto/ember-cli-flash/pull/28#issuecomment-81991231).  So it was slightly more complicated than not having the message disappear when mousing over.

I think we can definitely find a way to handle the progress bar not being accurate.

**Comment by cmcclure** [comment]
@sbatson5 Reading back through the ticket chain, it looks like the original intent was simply to not allow the flash message to destroy itself if the mouse was over the message at the end of the timer. Is that correct? Not to pause the timer/increase the total amount of time the message is displayed.

**Comment by sbatson5** [comment]
@cmcclure let me know this is a simple enough solution: https://github.com/poteto/ember-cli-flash/pull/239

**Comment by cmcclure** [comment]
That does address the core issue, but your tests are failing on `flash message: flash message is removed after timeout`. Also, this now means that the `progressDuration` property of the flash component will no longer actually represent how much time is left for the displayed message. 

Instead of pausing the timer, I'd probably just set a flag on hover that prevents the message from being destroyed. Then, on `mouseOut` check to see if the original timer is done and destroy if true. That would preserve the accuracy of the status bar, more closely respect the `timeout` attribute that the user sets, and (I think) get at the original intent of this feature which is to just prevent destroying when "focused".

**Comment by sbatson5** [comment]
Maybe I'm alone, but I prefer the pausing of the timer if we can solve the problem of showing the progress bar. I would find a progress bar that continues and ends but the message not disappearing to be confusing. Ideally it would look like:

![pause-on-hover](https://user-images.githubusercontent.com/881981/29935022-5d4daaa6-8e4b-11e7-9347-74729be3ee86.gif)

**Comment by cmcclure** [comment]
Fair enough. I have a use case that's maybe a bit outside the original intent of flash messages. I'm using the progress bar to visually refer to some background task that's being performed. The user hovering or not hovering on the message about the background task has no bearing on how long it actually takes.

**Comment by cmcclure** [comment]
PR for the interaction I described, [here](https://github.com/poteto/ember-cli-flash/pull/241)

**Comment by cmcclure** [comment]
@sbatson5 Any word on this? Thoughts on the PR?

**Comment by sbatson5** [comment]
Sorry for the delay (we're using bitbucket on this latest project, so I am not checking GH as often 😦 ).  It looks good to me. Need to figure out why the CircleCI build is failing. Are the tests passing locally for you?

**Comment by cmcclure** [comment]
Yeah, they're passing locally. Not sure what's up with your CI build.
