### ISSUE TITLE
remove requirement for providing a message

### ISSUE THREAD

**Issue by st-h** [poteto/ember-cli-flash#259]
We are happily using ember-cli-flash to display some custom notifications. Instead of just displaying a custom string, we sometimes have the need to render a component with additional functionality. This works pretty well, as we just need to pass the components name and then are able render it similar to what is shown in the docs.
```
this.get('flashMessages').add({
  component: 'group-undo-notification',
  model: group,
  message: '<none>',
  type: 'info'
});
```
However, this leads to situations where there simply is no message to display, as all the content is available through the component and additional objects that are passed in. This conflicts with the requirement to supply a message and we would like to propose to remove that requirement, as this just imposes unnecessary limitations to an otherwise very flexible addon.

**Comment by sbatson5** [comment]
This is something we should be able to do pretty easily. PRs are more than welcome! I can try to set some time aside for this in the next couple of weeks

**Comment by st-h** [comment]
Nice. I'll be happy to send over a PR, but wanted to check first if this would be a viable option to you at all.
