### ISSUE TITLE
Blueprint doesn't install test helper in Ember >= v2.17

### ISSUE THREAD

**Issue by bgentry** [poteto/ember-cli-flash#262]
I have some acceptance tests in my app which test for flash message content after an action.

After the v3 upgrade when these tests were converted to use `await`, then all started failing. It appears that `await` will wait for the ember-cli-flash timeout to end before moving on to the assertions that check for flash message content.

I created a demo app for this here: https://github.com/bgentry/ember3-flash-test-bug/blob/master/tests/acceptance/flash-text-test.js

Apologies if this turns out to be an Ember issue but I figured this is at least a good place to track it until that's sorted.

**Comment by rwjblue** [comment]
Thanks to @kategengler's sleuthing in slack, I believe this is a result of the custom test reopening behavior not running.

Basically, https://github.com/poteto/ember-cli-flash/blob/master/blueprints/ember-cli-flash/index.js#L9 needs to be updated to anchor onto something that is included in the current blueprints.

**Comment by rwjblue** [comment]
Although it strikes me, @bgentry did you perhaps accidentally delete this line:

```js
import './helpers/flash-message';
```

From your `tests/test-helper.js` file?

**Comment by bgentry** [comment]
@rwjblue ugh, yes, it turns out I did that at one point during the upgrade and forgot to replace it 🤦‍♂️  🤦‍♂️ 

I'll work up a PR for the install issue. Otherwise everything seems to be working fine on 3.0.

**Comment by bgentry** [comment]
I opened #263 to fix this. Thanks again @kategengler & @rwjblue.
