### ISSUE TITLE
usage of deprecated Ember.copy

### ISSUE THREAD

**Issue by bgentry** [poteto/ember-cli-flash#273]
Ember v3.3 deprecates `Copyable` and `Ember.copy`. [This file](https://github.com/poteto/ember-cli-flash/blob/7532006d7eecf1c16daa713fc47b31dd7335144d/addon/services/flash-messages.js) uses `copy` in two places.

I believe it's safe to just replace these specfic cases with `Object.assign` so I will submit a PR to do that.

**Comment by Dhaulagiri** [comment]
Fixed by https://github.com/poteto/ember-cli-flash/pull/274
