### ISSUE TITLE
Allow setting preventDuplicates when adding a flash message

### ISSUE THREAD

**Issue by makepanic** [poteto/ember-cli-flash#281]
Hi,

I was wondering why `preventDuplicates` isn't really working but it turns out that the addon uses the globally configured `preventDuplicates`.

This means if one wants to have some toasts to prevent duplicates, but not all, it's currently not possible.
One could change the addon behavior to read `preventDuplicates` when adding a flash.

This means a new precedence would look like: 

1. flashMessages.add `preventDuplicates`
2. `defaultPreventDuplicates`

If this is ok, I could open a PR to implement this behavior

**Comment by robclancy** [comment]
Here years later and expected this to be how it worked by default.
