### ISSUE TITLE
Upgrade to 1.7.0: Config undefined results in error

### ISSUE THREAD

**Issue by mattgraham1995** [poteto/ember-cli-flash#289]
https://github.com/poteto/ember-cli-flash/blob/e86f47dc963c5711d590a4ba12ca4d7a284fde4a/addon/services/flash-messages.js#L119

This property throws an error in my app's tests 
`Error: Assertion Failed: Cannot call get with 'flashMessageDefaults' on an undefined object.`

It seems that resolving the config from the registry returns `undefined` in this version.

**Comment by cythrawll** [comment]
Seems to be a problem in unit tests only.  But we need to add a `needs` for 'config:environment' seems to fix the issue. Opened PR #290

**Comment by olleolleolle** [comment]
#290 has been merged, does that help with this issue? Can this be closed, @mattgraham1995?

**Comment by mattgraham1995** [comment]
Yes that works.
