### ISSUE TITLE
DEPRECATION: Use of `merge` has been deprecated. Please use `assign` instead.

### ISSUE THREAD

**Issue by barryofguilder** [poteto/ember-cli-flash#291]
After upgrading to Ember 3.6, I get the following warning: "DEPRECATION: Use of `merge` has been deprecated. Please use `assign` instead." It's coming from the `utils/flash-message-options.js` file.

Here is the deprecation details: https://emberjs.com/deprecations/v3.x/#toc_ember-polyfills-deprecate-merge

**Comment by st-h** [comment]
yeah, just wanted to fix this deprecation only to find out that it already has been merged 20 days ago: https://github.com/poteto/ember-cli-flash/pull/288 

Any chance we can get a release soon?

**Comment by barryofguilder** [comment]
Duplicate of #288
