### ISSUE TITLE
Broken with embroider

### ISSUE THREAD

**Issue by villander** [poteto/ember-cli-flash#298]
Embroider: 0.3.4
ember-cli-flash: 1.7.1
ember-cli: 3.9.0

@ef4

![image](https://user-images.githubusercontent.com/10222774/57796317-73616e00-771e-11e9-9ee3-235644a03b60.png)

the line that this broken is here

![image](https://user-images.githubusercontent.com/10222774/57796798-58432e00-771f-11e9-8135-529833327846.png)

**Comment by ef4** [comment]
The issue here is confusion between named and default module exports. `guidFor` is a named export. So:

```js
// this works
import { guidFor } from '../utils/computed';
guidFor(whatever);

// and this works
import * as customComputed from '../utils/computed';
customComputed.guidFor(whatever);

// but this does not work.
import customComputed from '../utils/computed';
customComputed.guidFor(whatever);
```

This is a case where ember-cli historically allows a non-spec-compliant behavior.
