### ISSUE TITLE
Flash message mixin

### ISSUE THREAD

**Issue by AlexCppns** [poteto/ember-cli-flash#3]
Is there a reason why it is only injected in routes and controllers?

**Comment by poteto** [comment]
It's originally meant to mimic Rails' style flash messages. Is there a reason why you want to have a flash message inside of an Ember.Object? I'm not opposed to creating a mixin out of it, just curious what the use case is

**Comment by AlexCppns** [comment]
I am trying to inject it in another service. I am new to emberJS so I am not as familiar with the design patterns. Let me know if there is a better way to do it.

**Comment by AlexCppns** [comment]
Actually, is it supposed to work with an objectController? I just tried and I am getting an error:

 Uncaught TypeError: Cannot read property 'success' of undefined

My code looks like this:

```
import Ember from 'ember';

export default Ember.ObjectController.extend({
  handleChangeStateCallback: function(update, campaign, flash){
    update.done(function(data) {
      flash.success(data.notice);
      campaign.set('status', data.started);
    })
      .fail(function(xhr, textStatus, errorThrown) {
        alert('start campaign failed');
      });
  },
  actions: {
    deleteCampaign: function(){
      var campaign = this.get('model');
      campaign.deleteRecord();
      campaign.save();
    },
    changeCampaignState: function(action){
      var flash = Ember.get(this, 'flashes');
      var campaign = this.get('model');
      var update = this.agentGatewayService.changeCampaignState(campaign, action);
      this.handleChangeStateCallback(update, campaign, flash);
    }
  }
});

```

**Comment by gte451f** [comment]
I've found a need to use Flash messages in mixins.
+1 for access within Ember.Object, preferably a manual method.  Something like...

    import Ember from 'ember';
    import Flash from 'ember-cli-flash/mixin/flash';
    export default Ember.Mixin.create({
        actions:{
            someAction: function(){
                Flash.success('FLASH me!  Well, not THAT type of FLASH, the other less risqué' meaning of FLASH.  Put your shirt on.');
            }
        }
    });

**Comment by poteto** [comment]
Alright, I'll put this in the next milestone

**Comment by poteto** [comment]
Hey guys, I'm deciding against making a mixin out of the service, as isn't really necessary if your object is registered in the container. You can use `Ember.inject.service` to get a reference to the service.
