### ISSUE TITLE
Update Ember Versions to latest

### ISSUE THREAD

**Issue by sbatson5** [poteto/ember-cli-flash#305]
Our dependencies are set to 3.3 and I believe some of the tests for LTS are now failing.  It would be nice to update 3.9 and get ready for Octane -- this may require updating `ember-try` and dropping some older versions.

**Comment by makepanic** [comment]
I can try to take this issue. 

Does this mean that you want ember-source 3.9 as the new minimum version that it's running tests with?

**Comment by abhilashlr** [comment]
@sbatson5 @makepanic I've clubbed #306  and #305 into a single PR - #308
