### ISSUE TITLE
Update integration test

### ISSUE THREAD

**Issue by sbatson5** [poteto/ember-cli-flash#306]
The integration test currently on `master` is using the old `moduleForComponent` format.  I started working on updating it but ran into an issue with the timers.  We'll want to update the test to this format:

```
module('Integration | Component | flash message', function(hooks) {
  setupRenderingTest(hooks);
  ...
});
```

**Comment by esbanarango** [comment]
@sbatson5 I can help here ✋

**Comment by sbatson5** [comment]
Thanks! Let me know if you have questions.  Like I said, I gave it a stab but hit a road block when it came to testing the timing logic. i.e. 
- A message should disappear after x amount of seconds. 
- If you mouse over a message, it should not disappear, even if the timer has expired

I think the issue is around `await render` versus the old `this.render` -- I think `await` is causing all the lifecycle hooks to finish before the assertions run but I haven't had the time to investigate

**Comment by abhilashlr** [comment]
@sbatson5 @esbanarango  I've clubbed #306  and #305 into a single PR - #308

**Comment by esbanarango** [comment]
That's great @abhilashlr 🙏. I'll check if there is any remaining work to-do during weekend.

**Comment by abhilashlr** [comment]
Except for ember-release, and ember-canary the builds seem to pass. It is failing in CircleCI due to node version being 6. #309 attempts to address that.

**Comment by sbatson5** [comment]
Awesome! I should be able to take a look during some free time later today
