### ISSUE TITLE
Flash message after page refresh

### ISSUE THREAD

**Issue by tehmaestro** [poteto/ember-cli-flash#31]
Hey. Great plugin.
  I'm thinking about using it but here's what I need to do. After a user selects something from a dropdown and clicks the "Save" button, I need to refresh the page (I need to clear some i18n stuff).

 What would be the best way of showing a message after a page refresh? I'm thinking of storing the message in localStorage for example, and after the page refreshes, an initializer would check for the message in localStorage, and the message would get injected into `ember-cli-flash` and shown to the user.

 Does that sound ok? Thanks.

**Comment by poteto** [comment]
That's an interesting use case. Out of curiosity, why do you need to refresh the page to clear i18n? I'm hesitant about adding localStorage to the addon.

**Comment by tehmaestro** [comment]
Let's say the API requests have some information that is translated in English. Then the user goes to settings and changes the language to French. I want to refresh the page so that any "en" data in ember-data is flushed, and future API requests bring the correct data, in the correct language.

 Is there a better way to do this, one that doesn't require a page refresh? Thanks.

**Comment by rmariuzzo** [comment]
Interesting question, I would like to contribute somehow to make something similar. My use case is as follow:

 1. Save a _resource_.
 2. Do XHR request. Server says OK.
 3. Add a message: “The resources X was created!” (not render).
 4. Transition to another route like resource listing.
 5. Have the message rendered.

Is that possible @poteto?

**Comment by blimmer** [comment]
@rmariuzzo I use something similar to this. Does [this gist](https://gist.github.com/blimmer/7936ef285e3db911f82b13453ae543cc) help you?

**Comment by sbatson5** [comment]
@tehmaestro were you able to find a solution for this? Wondering if this issue can be closed.

**Comment by tehmaestro** [comment]
Hi, I don't use the plugin anymore. It can be closed.

If anybody wants to show a flash message after a page reload, probably the best pattern is storing an indicator and localStorage and reading that indicator after the page was refreshed.
