### ISSUE TITLE
Missing changelog for 1.8.0 release

### ISSUE THREAD

**Issue by lstrzebinczyk** [poteto/ember-cli-flash#319]
Hello. Can you please add changelog intro for 1.8.0 release?

**Comment by Turbo87** [comment]
@sbatson5 looks like the v2 release is also not in the changelog. would be great if this could be updated so that people can easily see what the breaking changes are.

**Comment by sbatson5** [comment]
Thanks for calling this out. I have some time set on my calendar next week to do some OSS work.  I'll add info for 1.8, 1.9 and 2

**Comment by lstrzebinczyk** [comment]
Thank you very much! One of the things, I believe, that sets the ember community from others is a very strong emphasis on keeping changelogs, which in turn makes it very easy to perform updates and maintenance work. Again, thank you for upholding that emphasis.
