### ISSUE TITLE
Cannot read property 'removeEventListener' of null

### ISSUE THREAD

**Issue by maxymczech** [poteto/ember-cli-flash#320]
Hello. Lately I have been getting this error message from `ember-cli-flash` in Sentry console of a project, error comes from `addon-tree-output/ember-cli-flash/components/flash-message.js`:

```
    willDestroyElement() {
      this._super(...arguments);
      this.element.removeEventListener('mouseenter', this._mouseEnter);
      this.element.removeEventListener('mouseleave', this._mouseLeave);
    }
```

Is it possible to wrap this call in `if (this.element) { ... }`?

**Comment by sbatson5** [comment]
Thank you for posting. This should be fixed now by https://github.com/poteto/ember-cli-flash/pull/315
