### ISSUE TITLE
@ember-decorators/component dependency missing

### ISSUE THREAD

**Issue by Turbo87** [poteto/ember-cli-flash#331]
https://github.com/poteto/ember-cli-flash/blob/master/addon/components/flash-message.js#L7 is referring to a `@ember-decorators/component` dependency, but in the `package.json` file it is only declared as a dev dependency.

**Comment by dimitrivdp** [comment]
Is it possible that commit 334 is not yet published on npm registry?

I did an install, and I got 

Uncaught (in promise) Error: Could not find module `@ember-decorators/component` imported from `ember-cli-flash/components/flash-message`
