### ISSUE TITLE
Cannot Use Selectors on Flash Message

### ISSUE THREAD

**Issue by jherdman** [poteto/ember-cli-flash#332]
Per ember-test-selectors:

<img width="637" alt="Screen Shot 2020-10-21 at 2 17 15 PM" src="https://user-images.githubusercontent.com/3300/96765676-23bdb200-13a8-11eb-992d-51d26cab315f.png">

Seems like the Flash Message component ought to either revert the `@tagName('')` change, or port to Glimmer.

**Comment by Techn1x** [comment]
The component contains `...attributes` so it should be fine for data test selectors.
https://github.com/poteto/ember-cli-flash/blob/49aec796a5123481f9b546cd53409455f38c0c41/addon/templates/components/flash-message.hbs#L1-L3

How are you applying the selectors to the component?
Also, does this help? https://github.com/simplabs/ember-test-selectors/issues/571

**Comment by jherdman** [comment]
I'm going to close this. It turns out we had a class and template override. Yay...
