### ISSUE TITLE
Using in Acceptance testing

### ISSUE THREAD

**Issue by kimf** [poteto/ember-cli-flash#4]
Hi.
I was trying to test that the flash is shown during an acceptance test..:
```
visit('/customers').then ->
  click('button:contains(\'Delete Customer\')').then ->
    equal currentRouteName(), 'customers.index'
    equal find('.flashMessage').text(), 'Customer was deleted'
```

It feels like maybe I'm just tired and totally overlooking something, but a pointer would really be helpful.
If i get this working I can write up a little tutorial and add it to the README...

**Comment by poteto** [comment]
@kimf What was the issue?

**Comment by kimf** [comment]
As soon as I added the line 
```equal find('.flashMessage').text(), 'Customer was deleted'```
the test failed, and I tried alot of different things, wich I can't remember right now, but gave up and just skipped that assert for now.

**Comment by poteto** [comment]
Ah okay. Maybe these will help?

- https://github.com/poteto/ember-cli-flash/blob/develop/tests/acceptance/integration-test.js
- https://github.com/poteto/ember-cli-flash/blob/develop/tests%2Fdummy%2Fapp%2Froutes%2Findex.js

**Comment by kimf** [comment]
I will try that..
Closing this, as the examples is there and the issue is on my end.

Thanks for your help.
