### ISSUE TITLE
Transition hooks for animating out

### ISSUE THREAD

**Issue by davidpike7** [poteto/ember-cli-flash#52]
Great addon!

I've just included a CSS keyframe animation to fade in the flash messages but just scratching my head as to how to fade them out again.

The addon seems to remove the messages instantly from the DOM, is there any way it could remove the active class first, then waiting for the JS transition event before removing it?

If you have approach that works already it would be fantastic to hear it.

Thanks

**Comment by poteto** [comment]
Thanks!

So the addon in its current state won't let you animate prior to removal, unfortunately. I can add a feature that will though

**Comment by davidpike7** [comment]
Yeah that would be great. Would give it that extra layer of polish :+1:

**Comment by truenorth** [comment]
I'd love to see support for animations :+1:
