### ISSUE TITLE
Error running acceptance tests with default helpers/flash-message.js

### ISSUE THREAD

**Issue by rtablada** [poteto/ember-cli-flash#57]
I've been scratching my head about this issue for a few days (trying the occasional hack while traveling) and haven't been able to run tests on a few of my projects recently.

I keep getting the error below:

```
Could not find module `ember-cli-flash/flash/object` imported from `my-app/tests/helpers/flash-message`
```

What's strange is that this is happening when running on Ubuntu or Codeship's CI servers and was working on my Mac dev environment until I refreshed my NPM cache... Not sure what seems to be the issue...

**Comment by poteto** [comment]
What version of ember-cli-flash are you on? Did you upgrade from an older version, or is it a fresh install?

That is quite strange. Does the addon work in your app, but not in tests?

**Comment by rtablada** [comment]
Ember CLI 0.2.3
Ember CLI Flash 1.1.1

Yeah the addon works fine but tests on Linux break.

What's weird is the build is fine, but seems to be breaking on tests (both with server and running `npm test`).

I'm trying to start with a scratch project to see where things are breaking and getting a better pattern for replicating this.

**Comment by poteto** [comment]
Yeah that does seem pretty odd. The only thing that comes to mind that could potentially be an OS issue is in the [blueprint's index](https://github.com/poteto/ember-cli-flash/blob/develop/blueprints/ember-cli-flash/index.js#L10), but I am requiring node's `EOL` which is cross platform. I haven't had the chance to test in a Linux environnment, but if you could let me know you find it would be very helpful. Thanks!

**Comment by rtablada** [comment]
I have confirmed that there is something going weird when running tests and have created a barebones project to show this going on: https://github.com/rtablada/materialize-break

And here is the breaking Travis build: https://travis-ci.org/rtablada/materialize-break/builds/58311333

Things seem to blow up on the initializer, but I've tested other addons with initializers and they don't seem to break when testing as shown by this build which pulls in ember-cli-simple-auth: https://travis-ci.org/rtablada/materialize-break/builds/58313851

Pinging in @truenorth because he was looking into this with me earlier too.

**Comment by poteto** [comment]
Thanks for that, I'll look into it now.

**Comment by poteto** [comment]
@rtablada So I made a [test repo](https://github.com/poteto/coolstory/commits/master) as well, and pushed it up. [Both of my builds passed](https://travis-ci.org/poteto/coolstory/builds) (1st commit was to install `ember-cli-flash`, 2nd was a simple acceptance test to verify that it was rendering it correctly). The only difference is that I didn't install `materialize`.

**Comment by truenorth** [comment]
I'll take another look at this later. I haven't eliminated the chance that this could be a loader problem yet

**Comment by poteto** [comment]
So the [problem is probably a conflict with `materialize`, [installing it](https://github.com/poteto/coolstory/commit/a6702f1d499ab11b745c76fc1b958ed5af452084) locally breaks tests for me on my machine as well as [Travis](https://travis-ci.org/poteto/coolstory/builds/58322663). Not exactly sure why they're conflicting, but I'll see if I can figure it out

**Comment by rtablada** [comment]
Yeah the combination of materialize, flash, and Phantom 1.9 seems to brick things.

**Comment by poteto** [comment]
Well, for now you can remove the test helper as well as the line it creates in `tests/test-helper`, and the flash addon should still be usable. Just take note that acceptance tests for flash without the helper will make it behave unintuitively

**Comment by ismay** [comment]
Problem exists for me as well. Can't really tell what's causing the problem, but my travis and commandline tests all succeed, whereas my `localhost:4200/tests` fail (when trying to test `ember-cli-flash`).
