### ISSUE TITLE
Link in message

### ISSUE THREAD

**Issue by karellm** [poteto/ember-cli-flash#58]
Hi,

Thanks for the component. Would it be possible to pass a link inside the message? Right now because of the escaping, it prints the HTML rather than rendering the link.

Thanks!

**Comment by poteto** [comment]
Hey, thanks for using this addon! You can do it by passing in your own arbitrary option to the component, something like this:

```js
Ember.get('flashMessages').add({
  message : 'Do something',
  href    : 'http://www.google.com',
  linkTo  : 'users.index'
});
```

```hbs
{{#each flashMessages.queue as |flash|}}
  {{#flash-message flash=flash as |component flash|}}
    <a href={{flash.href}}>{{flash.message}}</a>
   <!-- or if you want to link to somewhere in your app -->
   {{#link-to flash.linkTo}}{{flash.message}}{{/link-to}}
  {{/flash-message}}
{{/each}}
```

**Comment by karellm** [comment]
Thanks for the prompt answer. Ideally, I'd like to link only part of the message (or even have multiple links). Something like: 

```javascript
Ember.get('flashMessages').add({
  message : 'Do something that goes <a href="//google.com">here</a>.'
  // OR
    message : 'Do something that goes {{#link-to 'foo'}}here{{/link-to}}</a>.'
});
```

**Comment by jgwhite** [comment]
@poteto possible enhancement: how about adding the ability to specify a template? Something like:

```js
Ember.get('flashMessages').add({
  template: 'messages/success',
  message: 'It works!',
  linkTo: 'users.index'
});
```

**Comment by jgwhite** [comment]
@nikz pointed out that it may be possible to implement the above today using the partial helper, as in:

```js
Ember.get('flashMessages').add({
  template: 'messages/success',
  message: 'It works!',
  linkTo: 'users.index'
});
```

```hbs
{{#each flashMessages.queue as |flash|}}
  {{#flash-message flash=flash as |component flash|}}
    {{#if flash.template}}
      {{partial template}}
    {{/if}}
  {{/flash-message}}
{{/each}}
```

```hbs
{{! app/templates/messages/success.hbs }}

<h3>{{flash.message}}</h3>

{{#if flash.linkTo}}
  <p>Now you should go {{#link-to flash.linkTo}}here{{/link-to}}.</p>
{{else}}
  <p>There is nothing more to say.</p>
{{/if}}
```

**Comment by nikz** [comment]
Can confirm this works perfectly as described by @jgwhite - you do need to specify a message even if using `flash.template` though :)

Thanks for the add-on @poteto, it's amazing!

**Comment by poteto** [comment]
Yup, you can basically pass in any arbitrarily named key and it'll be added to the flash message object, and do more stuff with it by creating your own flash message component :) You could also use the `render` helper instead of the partial if you'd like to pass in some context, [see here](https://github.com/poteto/ember-cli-flash#example-use-case).

**Comment by karellm** [comment]
Great thanks! As a FYI, `{{render}}` is being deprecated. You should use `{{component}}` instead.
