### ISSUE TITLE
Message text not showing up in Ember-CLI 0.2.4

### ISSUE THREAD

**Issue by TayHobbs** [poteto/ember-cli-flash#64]
I recently updated my app to Ember-CLI 0.2.4 and now the flash messages will not display their text. I will get the red box where they should be, but they are just empty.

**Comment by poteto** [comment]
Upgrade to [`1.1.3`](https://github.com/poteto/ember-cli-flash/releases/tag/1.1.3) and you should be all good. The issue was with `template` and `templateName` being deprecated in components.

**Comment by TayHobbs** [comment]
I still experience the issue using Ember 1.12, ember-cli-flash 1.1.3 and Ember-CLI 0.2.4

**Comment by poteto** [comment]
@TayHobbs I found the issue, will release a hotfix shortly. Sorry!

**Comment by TayHobbs** [comment]
That did it! Thank you
