### ISSUE TITLE
Multiple flash messages are removed at the same time

### ISSUE THREAD

**Issue by lmcardle** [poteto/ember-cli-flash#68]
When I have multiple flash messages being displayed on the page at the same time, but initiated at different times, multiple flash messages are removed at the same time.  This appears to be random in which ones are removed together.  It is independent of the type of flash message it is.  Take a look at the attached gif.
![ember-cli-flash-multi-flash-remove](https://cloud.githubusercontent.com/assets/186442/7781668/3c1bdc32-00a8-11e5-9b01-9b3eaede323e.gif)

**Comment by poteto** [comment]
Hey, thanks for this. I'll investigate.

**Comment by JaroVDH** [comment]
I've just installed this and have also noticed this happening while testing.
Loaded in several sets of messages at once to see how they behave, and all got cleared when the first set's duration was over.
Some other funny business happened too, so I'll just do a step by step of what happens:
Similar to OP, I have a button to add a msg, except I add a set of 5 of them:
.add, .add + type 'error-custom' , .succes, .info and .add +sticky true.
I triggered two sets with a slight delay in between (2-3s):
![screen shot 2015-06-26 at 11 54 39](https://cloud.githubusercontent.com/assets/6927640/8375036/484108e4-1bfa-11e5-81e9-6d327bdb80f6.png)

When the first set is supposed to time out, all messages except two disappear:
![screen shot 2015-06-26 at 11 55 04](https://cloud.githubusercontent.com/assets/6927640/8375052/66da360e-1bfa-11e5-83a2-843c1364956f.png)
You'd expect the sticky messages to both remain, but the second one is replaced by the second Normal msg.

This second normal message then disappears at the time the second set of messages should have disappeared, leaving just the first sticky.
![screen shot 2015-06-26 at 11 55 25](https://cloud.githubusercontent.com/assets/6927640/8375068/8731c8f4-1bfa-11e5-8abf-999c82ddc843.png)


Hope this helps tracking down this bug. It's the only thing that's stopping me from replacing our old flashMessenger with this one.

**Comment by poteto** [comment]
Hi @lmcardle and @JaroVDH, can you try [1.3.0](https://github.com/poteto/ember-cli-flash/releases/tag/1.3.0) and see if the issue still persists? I have tested the latest ember-cli-flash release on Ember `1.12.0` and no longer have this issue.

**Comment by JaroVDH** [comment]
@poteto Still happening for me in 1.3.0, but with Ember 1.13.0.
If you have a way of including the addon into emberjs.jsbin.com I'll try and make one that triggers the issue for me.

**Comment by lmcardle** [comment]
I just upgraded to 1.3.3, it appears this issue is fixed.  Thanks @poteto
