### ISSUE TITLE
this.get('flashMessages') returns undefined. Pod structure?

### ISSUE THREAD

**Issue by ajrob27** [poteto/ember-cli-flash#71]
I'm trying to use ember-cli-flash with my application that is laid out in a pod structure. When calling `this.get('flashMessage')` from the controller, I get an error `Uncaught TypeError: Cannot read property 'success' of undefined`. 

Do you know if the pod structure might cause conflict? 

I will try to post an example of the error sometime tomorrow.

**Comment by thermokarst** [comment]
@ajrob27: I have an ember-cli 0.2.7 app set up with pods, and this add-on seems to work as advertised (thanks @poteto!!!). Two things come to mind though, first, in your example you are calling the wrong attribute, it should be ```this.get('flashMessages')```, plural. Also, if you are using ember-cli and its built-in test server, I believe you need to cycle the server off and on for it to pick up the changes to the project configuration. Good luck!

**Comment by Leooo** [comment]
I have the same issue, for some reason flashMessages is not injected into controllers (only see it in routes and views).

I thought there was a problem with injectionFactories and tried to inject the service into controllers through an initializer, but I still don't have any flashMessages property.

On Ember 1.12.1, Ember-cli 1.13.1, with pods

**Comment by Leooo** [comment]
Injecting the service into each controller which needs it with `flashMessages: Ember.inject.service(),` works well, strange..

**Comment by ajrob27** [comment]
@Leooo, I'm been out of Ember for quite a while now, I'm not going to be any help :disappointed: Sorry!

**Comment by thermokarst** [comment]
@Leooo: Did you modify any of the configuration defaults? I just set up a test environment with Ember 1.12.1, ember-cli 1.13.1, and ember-cli-flash 1.3.8, using pods, and the `flashMessages` object is available in a podified controller, and works as expected. I mentioned to @ajrob27 earlier this summer that he was referencing `flashMessage`, instead of `flashMessages` --- just want to double-check that that isn't the case for your issue. Maybe you can provide a more concrete example of what your controller looks like? Thanks!

**Comment by Leooo** [comment]
Thanks for checking @thermokarst. I didn't change anything in the config yet.  Yes, I'm using `flashMessages` not `flashMessage`. Honestly I have no clue where this come from, I have a big app so this may be on my side somewhere. For now I'm happy with adding the service individually to controllers (and long term we will only be using components). I'll definitely let you know if I see where this comes from, just wrote in the issue in case someone else gets the same problem.

**Comment by gonvaled** [comment]
Don't forget to restart `ember serve` after installing `ember-cli-clash`.
