### ISSUE TITLE
acceptance tests breaking with v1.2.0

### ISSUE THREAD

**Issue by palimpsests** [poteto/ember-cli-flash#76]
Hi, I'm running an application that is using Ember 1.12.1 and Ember-CLI 0.2.7.

My package.json has the following line: 

`"ember-cli-flash": "^1.1.4",`

Which updated the library to v1.2.0 on a recent npm install. My tests then started breaking with errors like:

`Error: Element .alert.alert-warning not found.`

If I run the test with the container visible, I can see the message flash, and the test hangs until the flash message disappears, and then it fails, and I get the aforementioned error.

Thank you for this library! It's great.

**Comment by mattmcmanus** [comment]
I ran into the same problem. Any tests, regardless of whether it's looking for anything will fail with a timeout. I poked around a little but but then reverted back to `1.1.4`.

**Comment by poteto** [comment]
Thanks for the report, I'm looking into it.

**Comment by poteto** [comment]
@palimpsests @mattmcmanus This should be fixed now in [`1.3.0`](https://github.com/poteto/ember-cli-flash/releases/tag/1.3.0), please give it a try and then run the below to re-generate the fixed test helper.

```sh
$ ember generate ember-cli-flash
```

**Comment by mattmcmanus** [comment]
Woot woot. Confirming that `1.3.0` fixes the issue. Thank you.
