### ISSUE TITLE
Uncaught Error: Computed Property declared without a property function

### ISSUE THREAD

**Issue by twest7** [poteto/ember-cli-flash#77]
With ember-cli 0.2.7 and ember-cli-flash 1.2.0 I'm getting this error stopping the entire Ember app from loading:

Uncaught Error: Computed Property declared without a property function
computed @ ember.debug.js:10586
add @ computed.js:17
(anonymous function) @ object.js:14

Stems from the following line within: https://github.com/poteto/ember-cli-flash/blob/develop/addon/flash/object.js

totalTimeout: customComputed.add('timeout', 'extendedTimeout').readOnly(),

**Comment by poteto** [comment]
Hey thanks for the report! This is a bug, I'll get a fix out soon. Sorry for the trouble

**Comment by poteto** [comment]
So I've been trying to reproduce the issue but I haven't had much luck. Could you share more details?

**Comment by nicolas-dular** [comment]
I've the same problems - @twest7 what ember version do you have? I am on 1.11

**Comment by truenorth** [comment]
almost certainly related to the computed property changes introduced in 1.12

**Comment by Jellyfishboy** [comment]
Also experiencing the same issue, using Ember 1.11.1.

**Comment by poteto** [comment]
Hey guys, you should try to upgrade your Ember versions to at least `1.12`. If this is not possible, you can use `1.1.2`– https://github.com/poteto/ember-cli-flash/releases/tag/1.1.2 which still works with Ember `1.11`.

**Comment by poteto** [comment]
@nicolas-dular @Jellyfishboy Good news, [`1.3.2`](https://github.com/poteto/ember-cli-flash/releases/tag/1.3.2) now works with Ember `1.11.x`, thanks to @truenorth :)

**Comment by nicolas-dular** [comment]
thanks @poteto in the meanwhile I've upgraded to ember `1.13` so I can use your libary and it works perfectly, thanks :+1:
