### ISSUE TITLE
#86 breaks current installs

### ISSUE THREAD

**Issue by raytiley** [poteto/ember-cli-flash#88]
I'm not super familiar with managing dependencies in addons but I think `ember-new-computed` needs to be in `dependencies` and not `devDependencies`.

Our builds broke with the new release that included the `ember-new-computed` (#86 ) as a dependency because `npm install` wasn't triggering the dependency to be installed.

**Comment by poteto** [comment]
Yeah you're right, it should be dependency. I'll push a fix shortly. Thanks for reporting!

**Comment by poteto** [comment]
@raytiley Let me know if https://github.com/poteto/ember-cli-flash/releases/tag/1.3.3 resolves your issue
