### ISSUE TITLE
Links inside the flash message are unable to be copied since click() makes the flash message to be closed

### ISSUE THREAD

**Issue by abhilashlr** [poteto/ember-cli-flash#90]
If the flash message has text say: "You can copy paste this &lt;URL&gt;" before you start highlighting, the flash message closes due to (https://github.com/poteto/ember-cli-flash/blob/develop/addon/components/flash-message.js#L90):

    click() {
        this._destroyFlashMessage();
    }

This should be made as option based as the above use case might not work. Alternatively, should I extend the flash-message component?

**Comment by jonathansamines** [comment]
The click behavior is really problematic for things like this. Could you consider removing this behavior, or at least allow controlling it? Using a close button, like foundation or bootstrap already have, isn´t a better behavior?

**Comment by anmolonruby** [comment]
What's the status of this issue?

**Comment by SirZach** [comment]
@abhilashlr you can write your own component that extends `flash-message` to remove the unwanted click behavior.
