### ISSUE TITLE
Uncaught TypeError: ember_new_computed.default.readOnly is not a function

### ISSUE THREAD

**Issue by pedrokost** [poteto/ember-cli-flash#92]
Using ember-cli-flash@1.3.3
Ember      : 1.13.6
Ember Data : 2.0.0-beta.1
jQuery     : 2.1.4

in line 14 of `object.js`:

```javascript
queue: ember_new_computed['default'].readOnly('flashService.queue'),
```

**Comment by pedrokost** [comment]
This "bug" was introduced in version `1.3.2`. All previous versions work fine (between `1.1.4` and `1.3.1`).

**Comment by pedrokost** [comment]
This issue is holding my upgrade to ember 2.0. Have others been able to upgrade ember with the latest version of the addon?

**Comment by grantovich** [comment]
I also see this error when attempting to use ember-cli-flash 1.3.4 with Ember 1.13.9. Tested with the not-yet-released 1.3.5 and still got the same error.

**Comment by poteto** [comment]
Thanks for the report and super sorry for not following up on this earlier. I'm looking into it, hopefully @rwjblue can also chime in

**Comment by rwjblue** [comment]
@poteto - Do we have a reproduction?

**Comment by grantovich** [comment]
I'm personally unable to reproduce the issue on a fresh-generated app using Ember-CLI 1.13.8, so it may be some interaction with the other dependencies of my app (and @pedrokost's). I haven't had time yet to investigate further, but I can confirm that downgrading to 1.3.1 also resolves the issue for me.

**Comment by rwjblue** [comment]
What is the output of `npm ls ember-new-computed`?

**Comment by rwjblue** [comment]
@poteto - I suspect the issue is that some other addon is including ember-new-computed@1.0.0 that is overriding the version that you are using here.  1.0.0 did not provide `computed.foo` macros, which would explain this issue.

Work around solution for that would be to use `import computed from 'ember-new-computed'; const { computed: { readOnly } } = Ember;` for the other ones, but I'd like to confirm the output of `npm ls ember-new-computed` above and get whatever is locked to 1.0.0 fixed.

**Comment by grantovich** [comment]
@rwjblue Thanks for the pointer! It appears I was using an older version of `ember-leaflet` that was locked to 1.0.0. The current version no longer uses `ember-new-computed` at all, so I should probably upgrade and the issue will be resolved.

I'm not completely familiar with the workings of NPM, but shouldn't this kind of conflict raise an error at `npm install` time? If one package requires exactly 1.0.0, and another requires exactly 1.0.2, they can't both get what they want...

**Comment by rwjblue** [comment]
npm allows both to be installed, and the ember-cli build pipeline is geared towards preventing duplication in the build output.  This leads to the "last" addon "winning" and clobbering other versions.

**Comment by rwjblue** [comment]
If we didn't do this, then you would have many versions of various deps shipped in `vendor.js`.

**Comment by grantovich** [comment]
> This leads to the "last" addon "winning" and clobbering other versions.

That... seems incredibly danger-prone. Given it's a situation where your app is almost guaranteed to be broken, shouldn't the build process at least warn you about it? (if not outright prevent you from building the app in such a state)
